services:
  keeweb:
    image: antelle/keeweb
    container_name: keeweb
    restart: unless-stopped
    ports:
      - "8844:80"
    volumes:
      - ./data:/keeweb/data
      - ./keeweb.conf:/etc/nginx/conf.d/keeweb.conf:ro