server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name _;

    root /keeweb;
    index index.html;

    server_tokens off;
    add_header X-Content-Type-Options nosniff;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ /\. {
        deny all;
    }
}